function a(){
  document.getElementById("kk").src="./images/interceptor-home-motorcycle1.jpg"
}
function b(){
    document.getElementById("kk").src="./images/motorcycle2.avif"
}
function c(){
    document.getElementById("kk").src="./images/motocycle3.avif"
}
function d(){
    document.getElementById("kk").src="./images/motorcycle4.avif"
}
function e(){
    document.getElementById("kk").src="./images/motorcycle5.avif"
}
function f(){
    document.getElementById("kk").src="./images/motocycle6.avif"
}
function g(){
    document.getElementById("kk").src="./images/motorcycle7.avif"
}
function h(){
    document.getElementById("kk").src="./images/motorcycle8.avif" 
}
function i(){
 document.getElementById("kk").src="./images/motorcycle9.avif"
}
// function i(){
//     document.getElementById("kk").
// }


// -------------Rides---------------

function r1(){
    document.getElementById("rr").src="./images/himalayan-odyssey-2023.avif"
  }
  function r2(){
      document.getElementById("rr").src="./images/rides2.avif" 
  }
  function r3(){
      document.getElementById("rr").src="./images/rides3.avif"
  }
  function r4(){
      document.getElementById("rr").src="./images/rides4.avif"
  }
  function r5(){
      document.getElementById("rr").src="./images/rides5.avif" 
  }
  function r6(){
      document.getElementById("rr").src="./images/rides6.avif"
  }

//   ----Apparels------

  function a1(){
    document.getElementById("aa").src="./images/royal-enfield-tcx.avif"
  }
  function a2(){
      document.getElementById("aa").src="./images/apparel2avif.avif"
  }
  function a3(){
      document.getElementById("aa").src="./images/apparel3.avif"
  }
  function a4(){
      document.getElementById("aa").src="./images/apparel4.avif"
  }
  function a5(){
      document.getElementById("aa").src="./images/apparel5.avif"
  }
  function a6(){
      document.getElementById("aa").src="./images/apparel6.avif"
  }

//   ------------Accessories---------------------

function ac1(){
    document.getElementById("acc").src="./images/gma-home.avif"
}
function ac2(){
    document.getElementById("acc").src="./images/accesory2.avif"
}


// -------------Locate Us--------------------

function L1(){
    document.getElementById("ll").src="./images/stores.avif"
}

function L2(){
    document.getElementById("ll").src="./images/locate2.avif"
}

function L3(){
    document.getElementById("ll").src="./images/locate3.avif"
}




